AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  profile-backend

  Sample SAM Template for profile-backend

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  GetProjectsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: projects/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /projects
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Profile Backend"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"
