AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  profile-backend

  Sample SAM Template for profile-backend

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  RestAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: ProfileBackend
      Description: Rest API for Profile Backend
      StageName: dev

  GetProjectsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetProjectsFunction
      Description: Get all projects
      CodeUri: projects/
      Handler: get_projects.get_projects_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          PROFILE_TABLE: !Ref ProfileBackendTable
      Events:
        GetProjectsApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref RestAPI
            Path: /projects
            Method: get

  GetProjectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetProjectFunction
      Description: Get project by id
      CodeUri: projects/
      Handler: get_project.get_project_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          PROFILE_TABLE: !Ref ProfileBackendTable
      Events:
        GetProjectApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref RestAPI
            Path: /projects/{project_id}
            Method: get

  ProfileBackendTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ProfileBackendTable
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  GetProjectsFunctionToProjectsTable:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: GetProjectsFunction
      Destination:
        Id: ProfileBackendTable
      Permissions:
        - Read

  GetProjectFunctionToProjectsTable:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: GetProjectFunction
      Destination:
        Id: ProfileBackendTable
      Permissions:
        - Read

Outputs:
  ProfileBackendApi:
    Description: "API Gateway endpoint URL for dev stage for Profile Backend"
    Value: !Sub "https://${RestAPI}.execute-api.${AWS::Region}.amazonaws.com/dev/"
