AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  profile-backend

  Sample SAM Template for profile-backend

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  RestAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: ProfileBackend
      Description: Rest API for Profile Backend
      StageName: dev

  GetProjectsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetProjectsFunction
      Description: Get projects
      CodeUri: projects/
      Handler: get_projects.get_projects_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          PROJECTS_TABLE: !Ref ProjectsTable
      Events:
        GetProjectsApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref RestAPI
            Path: /projects
            Method: get

  ProjectsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: ProfileBackend-Projects
      PrimaryKey:
        Name: id
        Type: String

  GetProjectsFunctionToProjectsTable:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: GetProjectsFunction
      Destination:
        Id: ProjectsTable
      Permissions:
        - Read

Outputs:
  ProfileBackendApi:
    Description: "API Gateway endpoint URL for dev stage for Profile Backend"
    Value: !Sub "https://${RestAPI}.execute-api.${AWS::Region}.amazonaws.com/dev/"
